In [3]:
from db_connect import create_connection, close_connection
import pandas as pd

c:\Users\zeyne\Automap\.venv\Lib\site-packages\paramiko\pkey.py:82: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  "cipher": algorithms.TripleDES,
c:\Users\zeyne\Automap\.venv\Lib\site-packages\paramiko\transport.py:253: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  "class": algorithms.TripleDES,

SSH tunnel established on local port: 55135

In [4]:
conn, server = create_connection()

Connected to Vertica!

In [3]:
query = """
SELECT column_name, data_type
FROM v_catalog.columns
WHERE table_schema = 'public'
AND table_name = 'main_tokenized'
ORDER BY ordinal_position;
"""
df = pd.read_sql(query, conn)
df.head()

  column_name     data_type
0     tableid           int
1       colid           int
2       rowid           int
3        term  varchar(200)
4   tokenized  varchar(200)

In [ ]:
query_1 = """
SELECT tableid, COUNT(*) AS n
FROM public.main_tokenized
GROUP BY tableid
ORDER BY n DESC;
"""
df_1 = pd.read_sql(query_1, conn)
df_1.head()

KeyboardInterrupt:

tableid  |   n    
-----------+--------
 119833525 | 210624
  58154545 | 189210
 102305662 | 181512
 103426083 | 166720
 120874431 | 137270
  76513727 | 102060
  75292212 |  93484
 139234877 |  93448
  98483472 |  89100
  47450014 |  87290
   5178922 |  86841
    314255 |  80232
 144823984 |  77896
  41462343 |  74632
  36602671 |  74580
 111871319 |  71568
 110470175 |  70909
  58083739 |  69342
  53975292 |  68555
 121601656 |  67773
  24040445 |  66918
 128068619 |  65184
 143238040 |  64612
 128728595 |  64568
  16469803 |  64564
  16469726 |  64408
  56496961 |  64259
  10332723 |  64212
 131090571 |  63990
  57677643 |  63855
 137722726 |  62784
 137722725 |  62784
  58154413 |  62585
    603169 |  62218
 134835939 |  61615
  95380469 |  61368
  71645162 |  61130
   1769795 |  61029
  58032437 |  60840
 144824041 |  60830
  15933260 |  60818
 142895009 |  60654
 115376139 |  60564
 113445322 |  60476
  61219833 |  60300
 105803910 |  59688
 143137688 |  58828
 103252864 |  58548
  98324577 |  58512
  43823679 |  58254
  61656111 |  58002
 107391215 |  57933
  11659370 |  57780
  87554556 |  57186
 124991064 |  57168
  58143468 |  56965
  61656121 |  56770
 135343449 |  56619
 117106832 |  56532
  42924123 |  56410
  74229572 |  55908
  89834739 |  55785
  33531507 |  55762
  13804791 |  55760
  11659373 |  55680
  93623040 |  55572
  23486771 |  55572
  69945784 |  55500
  69781124 |  55475
  52552541 |  55430
  95073950 |  55386
  22365115 |  54616
  36670324 |  54512
 100620847 |  54453
 111092124 |  54042
  79670337 |  54000
 123655982 |  53989
  61656124 |  53788
  91068454 |  53440
  36598615 |  52965
  98053248 |  52437
  63748013 |  52230
  72019190 |  51624
  53355226 |  50820
  49886725 |  50785
  63748014 |  50735
 113039080 |  50730
 113039079 |  50680
 120410374 |  50652
  20409520 |  50644
  73572615 |  50320
 106706080 |  50168
 111375318 |  50006
 119492191 |  49980
  53355225 |  49932
  44201508 |  49929
 114928718 |  49872
  22042262 |  49824
 103959431 |  49812
  22042264 |  49744
  80624700 |  49672
  24656033 |  49660
 114928719 |  49592
  97580409 |  49504
  80596583 |  49455
   3346245 |  49225
   9758523 |  49189
 127805728 |  49044
 121910410 |  48976
   5371264 |  48936
 144824028 |  48916
 139192745 |  48867
  16491411 |  48792
  95129092 |  48730
  69493646 |  48675
  83239050 |  48612
  47686371 |  48554
  77167355 |  48544
  69553754 |  48477
  53077952 |  48366
 140401278 |  48348
  38537994 |  48339
  37198860 |  48330
 139593114 |  48176
  69553756 |  48100
 123655981 |  48087
  26759862 |  47920
 141555607 |  47905
  26759863 |  47904
  84798204 |  47580
  16469801 |  47512
  92859726 |  47421
 142103845 |  47408
  41916439 |  47377
  61656114 |  47152
  86854419 |  47088
 111638196 |  47052
 106084641 |  46992
  35971495 |  46945
  21432449 |  46935
 106084642 |  46920
 106084644 |  46908
 106084643 |  46908
 106084640 |  46872
  47734220 |  46836
 106084639 |  46812
  52932171 |  46690
  52932173 |  46680
 139593115 |  46648
  12571370 |  46602
  52932172 |  46580
 112344407 |  46545
  57338407 |  46485
  95009356 |  46344
  80882485 |  46146
  67411900 |  45750
 110469874 |  45701
 114717479 |  45690
  80790758 |  45665
  15617587 |  45662
  40252357 |  45660
  23412351 |  45530
  23664999 |  45368
  23665002 |  45304
  28814622 |  45300
  95243103 |  45145
  14768270 |  45141
  28814624 |  45096
  27312933 |  45000
  62571466 |  44940
  23665000 |  44928
  90808953 |  44854
 130982119 |  44836
  16469739 |  44760
  75070238 |  44740
  67330835 |  44690
  83111153 |  44360
  80790755 |  44325
  21542650 |  44316
 109834650 |  44308
  91653062 |  44268
  61707243 |  44209
 111092121 |  44172
 122128088 |  44145
  80790759 |  44135
  38990557 |  44135
 109360285 |  44116
  25251033 |  44112
  38990556 |  44093
  95646051 |  44070
  95646052 |  44057
  21131733 |  43993
  80790756 |  43945
 107928315 |  43776
  89600846 |  43681
 136167416 |  43680
  97520265 |  43650
 119992500 |  43596
 119235663 |  43596
  80790757 |  43570
 121609212 |  43548
  69806106 |  43527
  55898623 |  43400
 104760748 |  43320
 119992459 |  43302
 100717917 |  43248
 143666112 |  43236
  12571351 |  43227
  38741397 |  43110
  83111154 |  43104
 126656361 |  43086
 120683295 |  43020
 137782083 |  42960
  25250990 |  42888
  34034828 |  42815
  59114461 |  42795
  59114460 |  42795
  51879005 |  42720
  25251268 |  42672
 111092119 |  42540
  25251084 |  42520
  25250853 |  42464
  25250786 |  42456
 119992408 |  42441
  45398230 |  42430
  25250586 |  42392
 132970879 |  42385
   3602176 |  42364
  85954490 |  42314
  30908049 |  42272
  65895424 |  42054
  38815545 |  42030
   3602174 |  41964
  80131528 |  41925
  11659372 |  41908
 134304583 |  41904
  80458369 |  41856
 123655980 |  41795
  69553755 |  41795
 141805710 |  41766
  58518766 |  41712
  34061098 |  41610
  48575608 |  41571
 130455465 |  41560
  72544796 |  41556
  57892614 |  41520
 129491663 |  41430
  72544795 |  41418
  51713007 |  41400
  28814627 |  41382
  66610624 |  41358
  79609833 |  41322
  80998782 |  41312
   3467774 |  41310
  87654936 |  41195
 103686379 |  41140
   4082160 |  41121
   4082161 |  41112
   4082159 |  41076
  86327716 |  41043
  80998721 |  41008
  11616073 |  41000
 126819159 |  40980
  10809158 |  40872
   4439503 |  40831
  57324531 |  40810
  80998675 |  40776
  80998905 |  40720
  80998693 |  40704
  80998335 |  40688
  80998299 |  40664
  80998588 |  40656
  37702252 |  40638
  31683796 |  40625
  37626975 |  40620
   3602173 |  40428
 119992440 |  40418
   7708642 |  40378
  80998737 |  40368
  51819172 |  40358
  80998724 |  40344
  67820449 |  40344
  80998591 |  40320
 102361528 |  40313
 102361529 |  40306
  23282618 |  40305
  80998887 |  40280
  80998343 |  40280
  38990558 |  40250
 120312656 |  40230
  80456944 |  40216
  85562287 |  40194
 133555240 |  40125
  34038493 |  40120
  38990559 |  40117
  80998654 |  40072
  28121286 |  40008
 127305965 |  40002
 105836351 |  40002
  68439448 |  40002
  29853215 |  40002
  24790037 |  40002
    522174 |  40002
 121430638 |  39992
 118009397 |  39992
  84187226 |  39992
  21094083 |  39992
  92928588 |  39970
   3602175 |  39948
  80998815 |  39920
  80998550 |  39856
  80998640 |  39784
  80998452 |  39736
  80998849 |  39712
 108781129 |  39672
  80998743 |  39632
  67409669 |  39540
  80998346 |  39520
  53826446 |  39494
 113246829 |  39474
  58255119 |  39402
  80998661 |  39376
  26752756 |  39376
  52766317 |  39368
  80998794 |  39320
 115144191 |  39294
 115144190 |  39285
  80998775 |  39232
 131054224 |  39222
  52766363 |  39221
  80998358 |  39144
  80998519 |  39080
  52766340 |  39074
  88142849 |  39068
  91681549 |  39060
  80998773 |  39048
  52766324 |  38976
  52766315 |  38948
  98959957 |  38892
  36837798 |  38844
  52766325 |  38829
  22042263 |  38824
 100605313 |  38790
  87555547 |  38768
  52766314 |  38633
 110679563 |  38619
 112287956 |  38589
  39499143 |  38580
 110412912 |  38574
   7713910 |  38550
   7713907 |  38545
  99954985 |  38532
 119235664 |  38507
  80998750 |  38408
  58584773 |  38348
  39499163 |  38265
  58584772 |  38264
 143460933 |  38260
 140193697 |  38256
  85359841 |  38234
 119992503 |  38220
   7221657 |  38185
  34020598 |  38180
  70633886 |  38157

In [3]:
query_2 = """
SELECT *
FROM public.main_tokenized
WHERE tableid = 75292212
LIMIT 50;
"""
df_2 = pd.read_sql(query_2, conn)
df_2.head()

    tableid  colid  rowid  term tokenized
0  75292212      0   4789    No
1  75292212      0   6717  That
2  75292212      0   6719   The
3  75292212      0   6774    To
4  75292212      0   7305   Was

xformer=> SELECT
xformer->     tableid,
xformer->     COUNT(*) AS tokens,
xformer->     COUNT(DISTINCT rowid) AS rows,
xformer->     COUNT(DISTINCT colid) AS cols
xformer-> FROM public.main_tokenized
xformer-> GROUP BY tableid
xformer-> ORDER BY rows DESC;
  tableid  | tokens | rows  | cols 
-----------+--------+-------+------
  75292212 |  93484 | 46742 |    2
 139234877 |  93448 | 46724 |    2
    314255 |  80232 | 40116 |    2
  15933260 |  60818 | 30409 |    2
 113445322 |  60476 | 30238 |    2
  11659370 |  57780 | 28890 |    2
  11659373 |  55680 | 27840 |    2
  77167355 |  48544 | 24272 |    2
  85954490 |  42314 | 21157 |    2

In [6]:
query_3 = """
SELECT term, tokenized
FROM public.main_tokenized
WHERE tableid = 75292212
AND tokenized IS NOT NULL
LIMIT 50;
"""
df_3 = pd.read_sql(query_3, conn)
df_3.head()

   term tokenized
0    No
1  That
2   The
3    To
4   Was

In [7]:
query_4 = """
SELECT rowid, colid, term, tokenized
FROM public.main_tokenized
WHERE tableid = 75292212
ORDER BY rowid, colid
LIMIT 100;
"""
df_4 = pd.read_sql(query_4, conn)
df_4.head()

   rowid  colid term tokenized
0      0      0    %
1      0      1    7         7
2      1      0    &
3      1      1   28        28
4      2      0    '

In [8]:
df_4

    rowid  colid   term tokenized
0       0      0      %
1       0      1      7         7
2       1      0      &
3       1      1     28        28
4       2      0      '
..    ...    ...    ...       ...
95     47      1      2         2
96     48      0     13        13
97     48      1     14        14
98     49      0  13000     13000
99     49      1      3         3

[100 rows x 4 columns]

In [ ]:
query_5 = """
SELECT
tableid,
COUNT(*) AS tokens,
COUNT(DISTINCT rowid) AS rows,
COUNT(DISTINCT colid) AS cols
FROM public.main_tokenized
GROUP BY tableid;
"""
df_5 = pd.read_sql(query_5, conn)
df_5.head()

In [3]:
query_6 = """
SELECT
    tableid,
    COUNT(*) AS total_rows,
    SUM(
        CASE
            WHEN tokenized IS NULL
                 OR TRIM(tokenized) = ''
            THEN 1 ELSE 0
        END
    ) AS null_tokens,
    SUM(
        CASE
            WHEN REGEXP_LIKE(tokenized, '^[0-9]+$')
            THEN 1 ELSE 0
        END
    ) AS numeric_tokens,
    SUM(
        CASE
            WHEN tokenized IS NOT NULL
                 AND TRIM(tokenized) <> ''
                 AND NOT REGEXP_LIKE(tokenized, '^[0-9]+$')
            THEN 1 ELSE 0
        END
    ) AS string_tokens
FROM public.main_tokenized
WHERE tableid IN (
    75292212,
    139234877,
    314255
)
GROUP BY tableid
ORDER BY total_rows DESC;
"""
df_6 = pd.read_sql(query_6, conn)
df_6

     tableid  total_rows  null_tokens  numeric_tokens  string_tokens
0   75292212       93484           69           46951          46464
1  139234877       93448          208           46924          46316
2     314255       80232           44           40450          39738

In [4]:
query_7 = """
SELECT tableid, term, tokenized
FROM public.main_tokenized
WHERE tableid IN (
    75292212,
    139234877,
    314255
)
AND (
    tokenized IS NULL
    OR TRIM(tokenized) = ''
)
LIMIT 20;
"""
df_7 = pd.read_sql(query_7, conn)
df_7

     tableid  term tokenized
0   75292212    No
1   75292212  That
2   75292212   The
3   75292212    To
4   75292212   Was
5   75292212  Will
6   75292212     [
7   75292212    []
8   75292212     ]
9   75292212     `
10  75292212     a
11  75292212    a)
12  75292212   and
13  75292212    as
14  75292212   for
15  75292212    in
16  75292212    is
17  75292212    no
18  75292212   not
19  75292212    of

In [5]:
query_8 = """
SELECT tableid, term, tokenized
FROM public.main_tokenized
WHERE tableid IN (
    75292212,
    139234877,
    314255
)
AND REGEXP_LIKE(tokenized, '^[0-9]+$')
LIMIT 20;
"""
df_8 = pd.read_sql(query_8, conn)
df_8

      tableid term tokenized
0      314255    0         0
1   139234877    1         1
2   139234877    1         1
3   139234877    1         1
4   139234877    1         1
5   139234877    1         1
6   139234877    1         1
7   139234877    1         1
8   139234877    1         1
9   139234877    1         1
10  139234877    1         1
11  139234877    1         1
12  139234877    1         1
13  139234877    1         1
14  139234877    1         1
15  139234877    1         1
16  139234877    1         1
17  139234877    1         1
18  139234877    1         1
19  139234877    1         1

In [7]:
query_9 = """
SELECT tableid, term, tokenized
FROM public.main_tokenized
WHERE tableid IN (
    75292212,
    139234877,
    314255
)
AND tokenized IS NOT NULL
AND TRIM(tokenized) <> ''
AND NOT REGEXP_LIKE(tokenized, '^[0-9]+$')
LIMIT 100;
"""
df_9 = pd.read_sql(query_9, conn)
df_9

      tableid                        term        tokenized
0   139234877  the the AT 0 0 0 0 0 0 0 0  0 0 0 0 0 0 0 0
1      314255                       0,006            0,006
2      314255                       0,014            0,014
3      314255                  0,7=milhão       0,7 milhão
4   139234877                       00.00            00.00
..        ...                         ...              ...
95  139234877                       1920s            1920s
96     314255                     1921-22          1921 22
97     314255                     1962-64          1962 64
98     314255                     1964-66          1964 66
99     314255                     1966-70          1966 70

[100 rows x 3 columns]

In [13]:
query_10 = """
SELECT 
    rowid,
    MAX(CASE WHEN colid = 0 THEN tokenized END) AS col_0,
    MAX(CASE WHEN colid = 1 THEN tokenized END) AS col_1,
    MAX(CASE WHEN colid = 2 THEN tokenized END) AS col_2,
    MAX(CASE WHEN colid = 3 THEN tokenized END) AS col_3,
    MAX(CASE WHEN colid = 4 THEN tokenized END) AS col_4,
    MAX(CASE WHEN colid = 5 THEN tokenized END) AS col_5,
    MAX(CASE WHEN colid = 6 THEN tokenized END) AS col_6,
    MAX(CASE WHEN colid = 7 THEN tokenized END) AS col_7
FROM public.main_tokenized
WHERE tableid = 119833525
GROUP BY rowid
ORDER BY rowid;
"""

df_10 = pd.read_sql(query_10, conn)

In [14]:
df_10.head(15)

,rowid,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7
0,0,alan gersony,brian mcdonnell,dan ryan,james macpherson,jeff westhaven,john adams,john hall,mark hall
1,1,584,607,580,619,613,583,576,575
2,2,67.38,34.27,31.28,34.58,35.19,51.54,29.26,29.16
3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
import pandas as pd

query_11 = """
SELECT rowid, colid, tokenized
FROM public.main_tokenized
WHERE tableid = 119833525
ORDER BY rowid, colid;
"""

df_raw = pd.read_sql(query_11, conn)

df_11 = df_raw.pivot(
    index='rowid', 
    columns='colid', 
    values='tokenized'
)

df_11.columns = [f"col_{c}" for c in df_11.columns]

# Display the dynamically reconstructed table
df_11

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,...,col_22,col_23,col_24,col_25,col_26,col_27,col_28,col_29,col_30,col_31
rowid,,,,,,,,,,,,,,,,,,,,,
0,alan gersony,brian mcdonnell,dan ryan,james macpherson,jeff westhaven,john adams,john hall,mark hall,matt mahoney,name,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,584,607,580,619,613,583,576,575,634,bib number,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,67.38,34.27,31.28,34.58,35.19,51.54,29.26,29.16,23.02,time mins.sec,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6578,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6579,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6580,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:

fast_sample_query = """
SELECT tableid, colid, rowid
FROM public.main_tokenized
LIMIT 50000;
"""
df_raw_samples = pd.read_sql(fast_sample_query, conn)

# 2. Count row occurrences in Python (Takes milliseconds!)
table_counts = df_raw_samples['tableid'].value_counts()

# 3. Filter for medium-sized tables (between 150 and 800 token cells)
medium_tables = table_counts[(table_counts >= 150) & (table_counts <= 800)]

# 4. Grab the top 5 unique IDs
sample_ids = medium_tables.index[:5].tolist()
print(f"🚀 Found 5 medium tables instantly in Python: {sample_ids}")

🚀 Found 5 medium tables instantly in Python: [108955944, 111583093, 8984229, 35952124, 35952273]

In [6]:
import pandas as pd

# 1. Verification Loop for your 5 chosen table IDs
for i, tid in enumerate(sample_ids, start=1):
    print(f"\n" + "="*50)
    print(f"📊 PROCESSING SAMPLE TABLE {i}/5 (ID: {tid})")
    print("="*50)
    
    # Fetch the precise matrix points for this specific table ID
    query = f"""
    SELECT rowid, colid, tokenized
    FROM public.main_tokenized
    WHERE tableid = {int(tid)}
    ORDER BY rowid, colid;
    """
    df_raw = pd.read_sql(query, conn)
    
    if df_raw.empty:
        print(f"⚠️ Table ID {tid} returned no rows. Skipping...")
        continue
        
    # Calculate and display the raw database token counts
    unique_rows = df_raw['rowid'].nunique()
    unique_cols = df_raw['colid'].nunique()
    print(f"📏 Raw Matrix Footprint: {unique_rows} rows x {unique_cols} columns ({len(df_raw)} total tokens)")
    
    try:
        # 2. Pivot the matrix points into an initial 2D layout
        # (Handling duplicate cell records gracefully with pivot_table using max aggregate)
        df_pivot = df_raw.pivot_table(
            index='rowid', 
            columns='colid', 
            values='tokenized', 
            aggfunc='max'
        )
        
        # 3. Transpose to align rows and columns structurally
        df_corrected = df_pivot.T
        
        # 4. Apply your Geometric Bottom-Up Header Finder
        header_idx = None
        for idx in reversed(df_corrected.index):
            row_data = df_corrected.loc[idx]
            valid_cells = [
                str(val).strip() for val in row_data.dropna()
                if str(val).strip() not in ("", "NaN", "nan", "null", "None")
            ]
            if len(valid_cells) > 0:
                header_idx = idx
                break
                
        if header_idx is not None:
            # Assign structural text strings found at the boundary edge as labels
            df_corrected.columns = df_corrected.loc[header_idx].values
            df_corrected = df_corrected.drop(index=header_idx, errors='ignore')
        else:
            print("⚠️ Could not dynamically establish a geometric text header. Using defaults.")
            df_corrected.columns = [f"col_{c}" for c in df_corrected.columns]
            
        # 5. Clean up tracking offsets, index parameters, and empty columns
        df_corrected = df_corrected.drop(index=0, errors='ignore') # Drop rowid 0 anchor if present
        df_corrected = df_corrected.loc[:, df_corrected.columns.notna()]
        df_corrected = df_corrected.dropna(how='all', axis=1)
        df_corrected.index.name = "runner_row_idx"
        
        print(f"✨ Reconstructed Table Dimensions: {df_corrected.shape[0]} rows x {df_corrected.shape[1]} columns")
        print("\n👀 Preview of reconstructed layout:")
        display(df_corrected.head(5))
        
    except Exception as e:
        print(f"❌ Failed to structurally reconstruct Table ID {tid} due to error: {str(e)}")

==================================================
📊 PROCESSING SAMPLE TABLE 1/5 (ID: 108955944)
==================================================
📏 Raw Matrix Footprint: 2991 rows x 2 columns (5982 total tokens)
✨ Reconstructed Table Dimensions: 0 rows x 0 columns

👀 Preview of reconstructed layout:

Empty DataFrame
Columns: []
Index: []

==================================================
📊 PROCESSING SAMPLE TABLE 2/5 (ID: 111583093)
==================================================
📏 Raw Matrix Footprint: 453 rows x 7 columns (3171 total tokens)
✨ Reconstructed Table Dimensions: 5 rows x 451 columns

👀 Preview of reconstructed layout:

,10 2003,03 1991,06 2011,11 1984,06 2005,05 1996,06 1984,06 2005,07 2010,05 2012,...,01 1953,08 1973,09 2007,03 1976,01 1988,n r,06 2010,10 1998,09 1942,05 1958
runner_row_idx,,,,,,,,,,,,,,,,,,,,,
1,po box 705 warrensburg ny 12885 0705,1 irongate ctr glens falls ny 12801 3471,po box 883 glens falls ny 12801 0883,rd 3 box 211 belles circle queensbury ny 12804...,136 glen st apt 3 glens falls ny 12801 4434,po box 2656 glens falls ny 12801 6656,640 bay rd queensbury ny 12804 1445,po box 201 north creek ny 12853 0201,po box 2 lake luzerne ny 12846 0002,42 ridge st glens falls ny 12801 3610,...,po box 306 lake luzerne ny 12846 0306,36 elm st warrensburg ny 12885 1625,po box 11 riparius ny 12862 0011,po box 2245 glens falls ny 12801 6245,po box 4392 queensbury ny 12804 0392,66 n church ln queensbury ny 12804 8053,po box 558 lake luzerne ny 12846 0558,c o richard hodge 44 louise lane lake george n...,po box 74 north creek ny 12853 0074,po box 2671 silver bay ny 12874 2671
2,charitable organization public foundations,charitable organization aids,educational organization community foundations,charitable organization,charitable organization nonmonetary support n.e.c,charitable organization health general rehabil...,charitable organization single organization su...,charitable organization human service organiza...,charitable organization educational services s...,charitable organization urban community econom...,...,business league,literary organization,charitable organization fire prevention protec...,charitable organization sports training facili...,charitable organization,4947 2 charitable trust form 990 filer,charitable organization ambulance emergency me...,charitable organization,civic league,social welfare organization
3,,,,,,,,,,,...,,,,,,,,,,
4,,,,,,,,,,,...,,,,,,,,,,
5,,,,,,,,,,,...,,,,,,,,,,

==================================================
📊 PROCESSING SAMPLE TABLE 3/5 (ID: 8984229)
==================================================
📏 Raw Matrix Footprint: 1198 rows x 4 columns (4792 total tokens)
✨ Reconstructed Table Dimensions: 2 rows x 94 columns

👀 Preview of reconstructed layout:

,describe other operating system available board,firnware bootloaders,flameman uboot,rootfs,storage device harddisk microdrive compact flash put rootfs,flameman dht walnut rootfs,device,class,devname,tested,...,please report any other working hardware here flamemaniii gmail.com,feel free add newer lines flameman dht walnut hardware_that_is_known_to_work_with_2,development,thinking new things should compatible free time constraints p,see also flameman dht walnut develop,you need pci riser,misc,see also flameman dht walnut proof,category:dht walnut,category:powerpc
runner_row_idx,,,,,,,,,,,,,,,,,,,,,
1,describe other operating system avalaible board,jtag ocd commander,partition,coming soon,install,coming soon,pin,addr,function,,...,please report any other working hardware here ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,,,,,,,,,,,...,NaN,,,,,,,,,

==================================================
📊 PROCESSING SAMPLE TABLE 4/5 (ID: 35952124)
==================================================
📏 Raw Matrix Footprint: 501 rows x 4 columns (2004 total tokens)
✨ Reconstructed Table Dimensions: 2 rows x 170 columns

👀 Preview of reconstructed layout:

,other,birthdate apr 09 1996,birthdate may 23 1973 date death jan 31 2002,birthdate sep 03 1940,birthdate may 04 1979,birthdate 1973,birthdate jun 08 1925 date death jan 15 2007,birthdate jul 06 1905 date death jan 05 1981,birthdate may 05 1985,birthdate jun 29 1925 date death jan 28 2003,...,birthdate jun 14 1975,birthdate mar 23 1941,birthdate dec 19 1971,birthdate apr 11 1982,birthdate jun 24 1914 date death jan 18 1960,birthdate apr 10 1910 date death jan 01 1996,birthdate oct 11 1907 date death jan 08 1998,birthdate feb 14 1924,birthdate sep 20 1918 date death jan 07 2002,birthdate oct 06 1933
runner_row_idx,,,,,,,,,,,,,,,,,,,,,
1,gender,female,female,female,female,female,female,female,female,female,...,male,male,male,male,female,female,male,female,female,female
2,bio,,,,,,,,,,...,,,,,,,,,,

==================================================
📊 PROCESSING SAMPLE TABLE 5/5 (ID: 35952273)
==================================================
📏 Raw Matrix Footprint: 501 rows x 4 columns (2004 total tokens)
✨ Reconstructed Table Dimensions: 2 rows x 107 columns

👀 Preview of reconstructed layout:

,birthdate oct 29 1954,birthdate aug 11 1921 date death jan 10 1992,birthdate nov 19 1972,birthdate sep 17 1980,birthdate feb 26 1990,birthdate may 23 1942,birthdate oct 20 1990,birthdate jun 10 1990,birthdate 1978,birthdate dec 11 1986,...,birthdate nov 11 1981,birthdate oct 17 1979,birthdate oct 31 1987,birthdate dec 27 1972,birthdate aug 08 1984,birthdate mar 25 1964,birthdate dec 15 1979,birthdate jul 03 1995,birthdate jun 27 1971,other
runner_row_idx,,,,,,,,,,,,,,,,,,,,,
1,male,male,male,male,male,male,male,female,male,male,...,female,male,male,male,male,male,male,female,male,gender
2,,,,,,,,,,,...,,,,,,,,yes,,bio

In [7]:
import pandas as pd

for i, tid in enumerate(sample_ids, start=1):
    print("\n" + "="*60)
    print(f"🔍 RAW DIAGNOSTIC FOR TABLE {i}/5 (ID: {tid})")
    print("="*60)
    
    # 1. Pull the exact raw rows
    query = f"""
    SELECT rowid, colid, tokenized
    FROM public.main_tokenized
    WHERE tableid = {int(tid)}
    ORDER BY rowid, colid;
    """
    df_raw = pd.read_sql(query, conn)
    
    if df_raw.empty:
        print(f"Table {tid} is empty.")
        continue
        
    print(f"Unique rowids: {df_raw['rowid'].nunique()} | Unique colids: {df_raw['colid'].nunique()}")
    
    # 2. Pivot without ANY aggressive cleanups or transpositions
    df_pivot = df_raw.pivot_table(
        index='rowid', 
        columns='colid', 
        values='tokenized', 
        aggfunc='max'
    )
    
    print("\n--- Raw Pivot Preview (First 5 Rows) ---")
    display(df_pivot.head(5))
    
    print("\n--- Raw Pivot Tail (Last 5 Rows) ---")
    display(df_pivot.tail(5))

============================================================
🔍 RAW DIAGNOSTIC FOR TABLE 1/5 (ID: 108955944)
============================================================
Unique rowids: 2991 | Unique colids: 2

--- Raw Pivot Preview (First 5 Rows) ---

colid 0                1
rowid
0               robertma
1            jeffreyhapy
2               robertma
3            jeffreyhapy
4        cheap wholesale

--- Raw Pivot Tail (Last 5 Rows) ---

colid     0                          1
rowid
2239   date  saturday 17 november 2012
2240   date  saturday 17 november 2012
2241   date    friday 16 november 2012
2242   date    friday 16 november 2012
2243   date    friday 16 november 2012

============================================================
🔍 RAW DIAGNOSTIC FOR TABLE 2/5 (ID: 111583093)
============================================================
Unique rowids: 453 | Unique colids: 7

--- Raw Pivot Preview (First 5 Rows) ---

colid,0,1,2,3,4,5,6
rowid,,,,,,,
0,reported asset income revenue amounts availabl...,NaN,NaN,NaN,NaN,NaN,NaN
1,acacia charities inc,po box 705 warrensburg ny 12885 0705,charitable organization public foundations,,,,10 2003
2,adirondack aids task force corporation c o ric...,1 irongate ctr glens falls ny 12801 3471,charitable organization aids,,,,03 1991
3,adirondack balloon festival foundation inc,po box 883 glens falls ny 12801 0883,educational organization community foundations,,,,06 2011
4,adirondack baptist church,rd 3 box 211 belles circle queensbury ny 12804...,charitable organization,,,,11 1984

--- Raw Pivot Tail (Last 5 Rows) ---

colid,0,1,2,3,4,5,6
rowid,,,,,,,
448,robert l tinker charitable remainder unitrust,66 n church ln queensbury ny 12804 8053,4947 2 charitable trust form 990 filer,,,,n r
449,rockwell falls ambulance service inc c o luzer...,po box 558 lake luzerne ny 12846 0558,charitable organization ambulance emergency me...,,,,06 2010
450,rotary district 7190 gift life inc c o john mucha,c o richard hodge 44 louise lane lake george n...,charitable organization,,,,10 1998
451,rotary international c o brenda p foley,po box 74 north creek ny 12853 0074,civic league,,,,09 1942
452,rotary international c o gerald crammond treas,po box 2671 silver bay ny 12874 2671,social welfare organization,,,,05 1958

============================================================
🔍 RAW DIAGNOSTIC FOR TABLE 3/5 (ID: 8984229)
============================================================
Unique rowids: 1198 | Unique colids: 4

--- Raw Pivot Preview (First 5 Rows) ---

colid                                        0    1         2    3
rowid
0      38 intermediate revisions 3 users shown  NaN       NaN  NaN
1                                   line 1,056  NaN  line 451  NaN
2                                   line 1,417  NaN  line 500  NaN
3                                   line 1,423  NaN  line 507  NaN
4                                   line 1,429  NaN  line 514  NaN

--- Raw Pivot Tail (Last 5 Rows) ---

colid    0    1 2                                   3
rowid
1193   NaN  NaN                                   NaN
1194   NaN  NaN    see also flameman dht walnut proof
1195   NaN  NaN                                   NaN
1196   NaN  NaN                   category:dht walnut
1197   NaN  NaN                      category:powerpc

============================================================
🔍 RAW DIAGNOSTIC FOR TABLE 4/5 (ID: 35952124)
============================================================
Unique rowids: 501 | Unique colids: 4

--- Raw Pivot Preview (First 5 Rows) ---

colid                0       1    2      3
rowid
0                 name  gender  bio  other
1        pauline black  female         NaN
2       pauline boraud  female         NaN
3         pauline boty  female         NaN
4      pauline boulton  female         NaN

--- Raw Pivot Tail (Last 5 Rows) ---

colid             0       1 2                      3
rowid
496     peg shirley  female    birthdate oct 06 1933
497       peg small  female                      NaN
498      peg stewar  female                      NaN
499     peg stewart  female                      NaN
500    peg stirling  female                      NaN

============================================================
🔍 RAW DIAGNOSTIC FOR TABLE 5/5 (ID: 35952273)
============================================================
Unique rowids: 501 | Unique colids: 4

--- Raw Pivot Preview (First 5 Rows) ---

colid                0       1 2    3
rowid
0       alex gregory 2    male    NaN
1      alex greinecker    male    NaN
2       alex griffiths  female    NaN
3        alex grizenko    male    NaN
4           alex guard    male    NaN

--- Raw Pivot Tail (Last 5 Rows) ---

colid               0       1    2      3
rowid
496    alex stevens 2    male         NaN
497    alex stevens 3  female         NaN
498    alex stewart 1    male         NaN
499    alex stewart 2    male         NaN
500              name  gender  bio  other

In [8]:
import pandas as pd

for i, tid in enumerate(sample_ids, start=1):
    print("\n" + "="*60)
    print(f"📊 RECONSTRUCTING TABLE {i}/5 (ID: {tid})")
    print("="*60)
    
    query = f"""
    SELECT rowid, colid, tokenized
    FROM public.main_tokenized
    WHERE tableid = {int(tid)}
    ORDER BY rowid, colid;
    """
    df_raw = pd.read_sql(query, conn)
    
    if df_raw.empty:
        continue
        
    # 1. Base Pivot (Keep the natural vertical orientation)
    df_pivot = df_raw.pivot_table(index='rowid', columns='colid', values='tokenized', aggfunc='max')
    
    # Define common header indicators to locate metadata rows
    header_keywords = {'name', 'gender', 'bio', 'other', 'date', 'amount', 'type', 'id', 'title', 'revenue'}
    
    header_idx = None
    
    # 2. Scan every row to check if it matches our header profiles
    for idx, row in df_pivot.iterrows():
        row_words = [str(val).lower().strip() for val in row.dropna()]
        
        # If any word in this row hits our target keyword profile, we've found our header!
        if any(any(kw in word for kw in header_keywords) for word in row_words):
            header_idx = idx
            break
            
    # 3. Apply the headers based on our discovery
    df_final = df_pivot.copy()
    if header_idx is not None:
        print(f"🎯 Header row discovered at rowid: {header_idx}")
        # Assign discovered text values as column names
        df_final.columns = [str(c).strip() for c in df_pivot.loc[header_idx].values]
        # Drop the header row from the data body
        df_final = df_final.drop(index=header_idx, errors='ignore')
    else:
        print("💡 No explicit text header row found. Auto-generating generic column names.")
        df_final.columns = [f"col_{c}" for c in df_pivot.columns]
        
    # 4. Universal Data Polishing
    # Remove any rows where all elements are NaN
    df_final = df_final.dropna(how='all', axis=0)
    # Ensure column headers themselves aren't NaN values
    df_final = df_final.loc[:, df_final.columns.notna()]
    
    print(f"✨ Final Verified Layout: {df_final.shape[0]} rows x {df_final.shape[1]} columns")
    display(df_final.head(5))

============================================================
📊 RECONSTRUCTING TABLE 1/5 (ID: 108955944)
============================================================
🎯 Header row discovered at rowid: 93
✨ Final Verified Layout: 2243 rows x 2 columns

            idocunksnunk
rowid
0               robertma
1            jeffreyhapy
2               robertma
3            jeffreyhapy
4        cheap wholesale

============================================================
📊 RECONSTRUCTING TABLE 2/5 (ID: 111583093)
============================================================
🎯 Header row discovered at rowid: 0
✨ Final Verified Layout: 452 rows x 7 columns

,reported asset income revenue amounts available membership data download,nan,nan,nan,nan,nan,nan
rowid,,,,,,,
1,acacia charities inc,po box 705 warrensburg ny 12885 0705,charitable organization public foundations,,,,10 2003
2,adirondack aids task force corporation c o ric...,1 irongate ctr glens falls ny 12801 3471,charitable organization aids,,,,03 1991
3,adirondack balloon festival foundation inc,po box 883 glens falls ny 12801 0883,educational organization community foundations,,,,06 2011
4,adirondack baptist church,rd 3 box 211 belles circle queensbury ny 12804...,charitable organization,,,,11 1984
5,adirondack business school partnership inc c o...,136 glen st apt 3 glens falls ny 12801 4434,charitable organization nonmonetary support n.e.c,,,,06 2005

============================================================
📊 RECONSTRUCTING TABLE 3/5 (ID: 8984229)
============================================================
🎯 Header row discovered at rowid: 19
✨ Final Verified Layout: 1159 rows x 4 columns

,,describe other operating system avalaible board,,describe other operating system available board
rowid,,,,
0,38 intermediate revisions 3 users shown,NaN,NaN,NaN
1,"line 1,056",NaN,line 451,NaN
2,"line 1,417",NaN,line 500,NaN
3,"line 1,423",NaN,line 507,NaN
4,"line 1,429",NaN,line 514,NaN

============================================================
📊 RECONSTRUCTING TABLE 4/5 (ID: 35952124)
============================================================
🎯 Header row discovered at rowid: 0
✨ Final Verified Layout: 500 rows x 4 columns

                  name  gender bio other
rowid
1        pauline black  female       NaN
2       pauline boraud  female       NaN
3         pauline boty  female       NaN
4      pauline boulton  female       NaN
5       pauline bouvet  female       NaN

============================================================
📊 RECONSTRUCTING TABLE 5/5 (ID: 35952273)
============================================================
🎯 Header row discovered at rowid: 10
✨ Final Verified Layout: 500 rows x 4 columns

            alex hajdu    male   birthdate oct 29 1954
rowid
0       alex gregory 2    male                     NaN
1      alex greinecker    male                     NaN
2       alex griffiths  female                     NaN
3        alex grizenko    male                     NaN
4           alex guard    male                     NaN

In [9]:
import pandas as pd

for i, tid in enumerate(sample_ids, start=1):
    print("\n" + "="*60)
    print(f"📊 VERTICAL RECONSTRUCTION FOR TABLE {i}/5 (ID: {tid})")
    print("="*60)
    
    # 1. Fetch data ordered by its natural row sequence
    query = f"""
    SELECT rowid, colid, tokenized
    FROM public.main_tokenized
    WHERE tableid = {int(tid)}
    ORDER BY rowid, colid;
    """
    df_raw = pd.read_sql(query, conn)
    
    if df_raw.empty:
        continue
        
    # 2. Pivot into a clean vertical table layout
    df_vertical = df_raw.pivot_table(index='rowid', columns='colid', values='tokenized', aggfunc='max')
    
    # Define keywords that represent column schema definitions
    header_keywords = {'name', 'gender', 'bio', 'other', 'date', 'amount', 'type', 'id', 'title', 'revenue', 'number', 'time'}
    
    header_idx = None
    
    # 3. Locate the header row vertically
    for idx, row in df_vertical.iterrows():
        row_words = [str(val).lower().strip() for val in row.dropna()]
        if any(any(kw in word for kw in header_keywords) for word in row_words):
            header_idx = idx
            break
            
    # 4. Extract headers or fallback to generic naming
    df_final = df_vertical.copy()
    if header_idx is not None:
        print(f"🎯 Header row found at vertical index rowid: {header_idx}")
        df_final.columns = [str(c).strip() for c in df_vertical.loc[header_idx].values]
        df_final = df_final.drop(index=header_idx, errors='ignore')
    else:
        print("💡 No explicit text headers detected. Keeping numeric column names.")
        df_final.columns = [f"col_{c}" for c in df_vertical.columns]
        
    # 5. Drop fully empty spacer rows
    df_final = df_final.dropna(how='all', axis=0)
    df_final = df_final.loc[:, df_final.columns.notna()]
    
    print(f"✨ Final Vertical Table Shape: {df_final.shape[0]} rows x {df_final.shape[1]} columns")
    display(df_final.head(5))

============================================================
📊 VERTICAL RECONSTRUCTION FOR TABLE 1/5 (ID: 108955944)
============================================================
🎯 Header row found at vertical index rowid: 93
✨ Final Vertical Table Shape: 2243 rows x 2 columns

            idocunksnunk
rowid
0               robertma
1            jeffreyhapy
2               robertma
3            jeffreyhapy
4        cheap wholesale

============================================================
📊 VERTICAL RECONSTRUCTION FOR TABLE 2/5 (ID: 111583093)
============================================================
🎯 Header row found at vertical index rowid: 0
✨ Final Vertical Table Shape: 452 rows x 7 columns

,reported asset income revenue amounts available membership data download,nan,nan,nan,nan,nan,nan
rowid,,,,,,,
1,acacia charities inc,po box 705 warrensburg ny 12885 0705,charitable organization public foundations,,,,10 2003
2,adirondack aids task force corporation c o ric...,1 irongate ctr glens falls ny 12801 3471,charitable organization aids,,,,03 1991
3,adirondack balloon festival foundation inc,po box 883 glens falls ny 12801 0883,educational organization community foundations,,,,06 2011
4,adirondack baptist church,rd 3 box 211 belles circle queensbury ny 12804...,charitable organization,,,,11 1984
5,adirondack business school partnership inc c o...,136 glen st apt 3 glens falls ny 12801 4434,charitable organization nonmonetary support n.e.c,,,,06 2005

============================================================
📊 VERTICAL RECONSTRUCTION FOR TABLE 3/5 (ID: 8984229)
============================================================
🎯 Header row found at vertical index rowid: 19
✨ Final Vertical Table Shape: 1159 rows x 4 columns

,,describe other operating system avalaible board,,describe other operating system available board
rowid,,,,
0,38 intermediate revisions 3 users shown,NaN,NaN,NaN
1,"line 1,056",NaN,line 451,NaN
2,"line 1,417",NaN,line 500,NaN
3,"line 1,423",NaN,line 507,NaN
4,"line 1,429",NaN,line 514,NaN

============================================================
📊 VERTICAL RECONSTRUCTION FOR TABLE 4/5 (ID: 35952124)
============================================================
🎯 Header row found at vertical index rowid: 0
✨ Final Vertical Table Shape: 500 rows x 4 columns

                  name  gender bio other
rowid
1        pauline black  female       NaN
2       pauline boraud  female       NaN
3         pauline boty  female       NaN
4      pauline boulton  female       NaN
5       pauline bouvet  female       NaN

============================================================
📊 VERTICAL RECONSTRUCTION FOR TABLE 5/5 (ID: 35952273)
============================================================
🎯 Header row found at vertical index rowid: 10
✨ Final Vertical Table Shape: 500 rows x 4 columns

            alex hajdu    male   birthdate oct 29 1954
rowid
0       alex gregory 2    male                     NaN
1      alex greinecker    male                     NaN
2       alex griffiths  female                     NaN
3        alex grizenko    male                     NaN
4           alex guard    male                     NaN

In [11]:
import pandas as pd

for i, tid in enumerate(sample_ids, start=1):
    print("\n" + "="*60)
    print(f"📊 VERTICAL RECONSTRUCTION FOR TABLE {i}/5 (ID: {tid})")
    print("="*60)
    
    # 1. Fetch data ordered by its natural coordinate sequence
    query = f"""
    SELECT rowid, colid, tokenized
    FROM public.main_tokenized
    WHERE tableid = {int(tid)}
    ORDER BY rowid, colid;
    """
    df_raw = pd.read_sql(query, conn)
    
    if df_raw.empty:
        print(f"⚠️ Table ID {tid} returned no data.")
        continue
        
    # 2. Convert literal string traps ("NaN", "None", spaces) into real Pandas Nulls
    df_raw['tokenized'] = df_raw['tokenized'].astype(str).str.strip()
    df_raw['tokenized'] = df_raw['tokenized'].replace(['NaN', 'nan', 'null', 'None', 'none', ''], pd.NA)
    
    # 3. Pivot into the natural vertical table layout
    df_vertical = df_raw.pivot_table(
        index='rowid', 
        columns='colid', 
        values='tokenized', 
        aggfunc='max'
    )
    df_final = df_vertical.dropna(how='all', axis=0).dropna(how='all', axis=1)
    
    # 5. Clean up column label names cleanly using standard indexing
    df_final.columns = [f"col_{c}" for c in df_final.columns]
    df_final.index.name = "row_id"
    
    print(f"✨ Final Vertical Matrix Dimensions: {df_final.shape[0]} rows x {df_final.shape[1]} columns")
    display(df_final.head(10))

============================================================
📊 VERTICAL RECONSTRUCTION FOR TABLE 1/5 (ID: 108955944)
============================================================
✨ Final Vertical Matrix Dimensions: 2243 rows x 2 columns

       col_0                    col_1
row_id
0        NaN                 robertma
1        NaN              jeffreyhapy
2        NaN                 robertma
3        NaN              jeffreyhapy
4        NaN          cheap wholesale
5        NaN    cheap college jerseys
6        NaN  cheap wholesale jerseys
7        NaN        cheap nfl jerseys
8        NaN    wholesale nfl jerseys
9        NaN        nfl jerseys cheap

============================================================
📊 VERTICAL RECONSTRUCTION FOR TABLE 2/5 (ID: 111583093)
============================================================
✨ Final Vertical Matrix Dimensions: 453 rows x 7 columns

,col_0,col_1,col_2,col_3,col_4,col_5,col_6
row_id,,,,,,,
0,reported asset income revenue amounts availabl...,NaN,NaN,NaN,NaN,NaN,NaN
1,acacia charities inc,po box 705 warrensburg ny 12885 0705,charitable organization public foundations,NaN,NaN,NaN,10 2003
2,adirondack aids task force corporation c o ric...,1 irongate ctr glens falls ny 12801 3471,charitable organization aids,NaN,NaN,NaN,03 1991
3,adirondack balloon festival foundation inc,po box 883 glens falls ny 12801 0883,educational organization community foundations,NaN,NaN,NaN,06 2011
4,adirondack baptist church,rd 3 box 211 belles circle queensbury ny 12804...,charitable organization,NaN,NaN,NaN,11 1984
5,adirondack business school partnership inc c o...,136 glen st apt 3 glens falls ny 12801 4434,charitable organization nonmonetary support n.e.c,NaN,NaN,NaN,06 2005
6,adirondack civil war round table c o donald w ...,po box 2656 glens falls ny 12801 6656,charitable organization health general rehabil...,NaN,NaN,NaN,05 1996
7,adirondack community college foundation inc,640 bay rd queensbury ny 12804 1445,charitable organization single organization su...,NaN,NaN,NaN,06 1984
8,adirondack community outreach center inc,po box 201 north creek ny 12853 0201,charitable organization human service organiza...,NaN,NaN,NaN,06 2005
9,adirondack folk school incorporated c o james ...,po box 2 lake luzerne ny 12846 0002,charitable organization educational services s...,NaN,NaN,NaN,07 2010

============================================================
📊 VERTICAL RECONSTRUCTION FOR TABLE 3/5 (ID: 8984229)
============================================================
✨ Final Vertical Matrix Dimensions: 718 rows x 4 columns

                                          col_0 col_1     col_2 col_3
row_id
0       38 intermediate revisions 3 users shown   NaN       NaN   NaN
1                                    line 1,056   NaN  line 451   NaN
2                                    line 1,417   NaN  line 500   NaN
3                                    line 1,423   NaN  line 507   NaN
4                                    line 1,429   NaN  line 514   NaN
5                                    line 1,435   NaN  line 521   NaN
6                                    line 1,441   NaN  line 528   NaN
7                                    line 1,447   NaN  line 535   NaN
8                                    line 1,459   NaN  line 555   NaN
9                                    line 1,473   NaN  line 568   NaN

============================================================
📊 VERTICAL RECONSTRUCTION FOR TABLE 4/5 (ID: 35952124)
============================================================
✨ Final Vertical Matrix Dimensions: 501 rows x 4 columns

                       col_0   col_1 col_2                  col_3
row_id
0                       name  gender   bio                  other
1              pauline black  female   NaN                    NaN
2             pauline boraud  female   NaN                    NaN
3               pauline boty  female   NaN                    NaN
4            pauline boulton  female   NaN                    NaN
5             pauline bouvet  female   NaN                    NaN
6             pauline burlet  female   NaN  birthdate apr 09 1996
7             pauline cadell  female   NaN                    NaN
8           pauline campbell  female   NaN                    NaN
9       pauline campton lowe  female   NaN                    NaN

============================================================
📊 VERTICAL RECONSTRUCTION FOR TABLE 5/5 (ID: 35952273)
============================================================
✨ Final Vertical Matrix Dimensions: 501 rows x 4 columns

                   col_0   col_1 col_2 col_3
row_id
0         alex gregory 2    male   NaN   NaN
1        alex greinecker    male   NaN   NaN
2         alex griffiths  female   NaN   NaN
3          alex grizenko    male   NaN   NaN
4             alex guard    male   NaN   NaN
5              alex guld    male   NaN   NaN
6         alex gulrajani    male   NaN   NaN
7            alex gushin    male   NaN   NaN
8       alex gutenmakher    male   NaN   NaN
9             alex habon    male   NaN   NaN